apiVersion: vc.io/v1beta1
kind: VcAgent
metadata:
  name: vcagent
  namespace: vcagent
spec:
  agent.zone.name: my-zone # (optional) name of the zone of the host
  agent.key: replace-me # replace with your VC agent key
  agent.endpoint.host: ingress-red-saas.vc.io # the monitoring ingress endpoint
  agent.endpoint.port: 443 # the monitoring ingress endpoint port, wrapped in quotes
  agent.env:
    VC_AGENT_TAGS: example
  cluster.name: replace-me # replace with the name of your Kubernetes cluster
  config.files:
    configuration.yaml: |
      # You can leave this empty, or use this to configure your vc agent.
      # See https://docs.vc.io/setup_and_manage/host_agent/on/kubernetes/
