apiVersion: vc.io/v1
kind: VcAgent
metadata:
  name: vcagent
  namespace: vcagent
spec:
  zone:
    name: edited-zone # (optional) name of the zone of the host
  cluster:
      name: my-cluster
  agent:
    key: replace-key # replace with your VC agent key
    endpointHost: vc.io
    endpointPort: "443"
    env: {}
    configuration_yaml: |
      # You can leave this empty, or use this to configure your vc agent.
      # See https://docs.vc.io/setup_and_manage/host_agent/on/kubernetes/
