//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
(c) Copyright IBM Corp.
(c) Copyright VC Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInfo) DeepCopyInto(out *ResourceInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInfo.
func (in *ResourceInfo) DeepCopy() *ResourceInfo {
	if in == nil {
		return nil
	}
	out := new(ResourceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcAgent) DeepCopyInto(out *VcAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcAgent.
func (in *VcAgent) DeepCopy() *VcAgent {
	if in == nil {
		return nil
	}
	out := new(VcAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VcAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcAgentList) DeepCopyInto(out *VcAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VcAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcAgentList.
func (in *VcAgentList) DeepCopy() *VcAgentList {
	if in == nil {
		return nil
	}
	out := new(VcAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VcAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcAgentSpec) DeepCopyInto(out *VcAgentSpec) {
	*out = *in
	if in.ConfigurationFiles != nil {
		in, out := &in.ConfigurationFiles, &out.ConfigurationFiles
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.AgentCpuReq = in.AgentCpuReq.DeepCopy()
	out.AgentCpuLim = in.AgentCpuLim.DeepCopy()
	out.AgentMemReq = in.AgentMemReq.DeepCopy()
	out.AgentMemLim = in.AgentMemLim.DeepCopy()
	if in.AgentEnv != nil {
		in, out := &in.AgentEnv, &out.AgentEnv
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcAgentSpec.
func (in *VcAgentSpec) DeepCopy() *VcAgentSpec {
	if in == nil {
		return nil
	}
	out := new(VcAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcAgentStatus) DeepCopyInto(out *VcAgentStatus) {
	*out = *in
	out.ServiceAccount = in.ServiceAccount
	out.ClusterRole = in.ClusterRole
	out.ClusterRoleBinding = in.ClusterRoleBinding
	out.Secret = in.Secret
	out.ConfigMap = in.ConfigMap
	out.DaemonSet = in.DaemonSet
	out.LeadingAgentPod = in.LeadingAgentPod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcAgentStatus.
func (in *VcAgentStatus) DeepCopy() *VcAgentStatus {
	if in == nil {
		return nil
	}
	out := new(VcAgentStatus)
	in.DeepCopyInto(out)
	return out
}
